steps:
# === Étape 1 : Tests unitaires ===
- name: 'python:3.11'
  entrypoint: bash
  args:
    - -c
    - |
      pip install -r requirements.txt
      echo " Début des tests..."
      pytest || echo " Avertissement: aucun test trouvé ou tests ignorés"

# === Étape 2 : Build de l’image Docker ===
- name: 'gcr.io/cloud-builders/docker'
  args:
    ['build', '-t', 'gcr.io/simplifia-hackathon/toxic-detection-api:$COMMIT_SHA', '.']

# === Étape 3 : Push de l’image sur Google Container Registry ===
- name: 'gcr.io/cloud-builders/docker'
  args:
    ['push', 'gcr.io/simplifia-hackathon/toxic-detection-api:$COMMIT_SHA']

# === Étape 4 : Déploiement automatique sur Kubernetes ===
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
    - -c
    - |
      echo " Configuration kubectl..."
      gcloud container clusters get-credentials my-cluster --zone europe-west1-b --project simplifia-hackathon
      echo " Déploiement de la nouvelle image sur GKE..."
      kubectl set image deployment/toxic-detection-api api=gcr.io/simplifia-hackathon/toxic-detection-api:$COMMIT_SHA
      kubectl rollout status deployment/toxic-detection-api

# === Étape 5 : (Optionnel) Lancer un pipeline Vertex AI ===
- name: 'python:3.11'
  entrypoint: python
  args: ['trigger_pipeline.py']

images:
  - 'gcr.io/$PROJECT_ID/toxic-detection-api:$COMMIT_SHA'
